services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Scheduler\:
    resource: '../../src/Scheduler/*'
    exclude: '../../src/Scheduler/{Entity,Repository,Library}'
    public: true